version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://root:YCEcHRQirdMwWetpThNOSPtLAKJWhLAD@viaduct.proxy.rlwy.net:48277/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=YCEcHRQirdMwWetpThNOSPtLAKJWhLAD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_EMAIL_SENDER_EMAIL=elsyum0@gmail.com
      - SPRING_EMAIL_SENDER_NAME=Essencia
      - SPRING_EMAIL_SENDER_PASSWORD=tmtqvpcgffawmbaj
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=railway
      - MYSQL_ROOT_PASSWORD=YCEcHRQirdMwWetpThNOSPtLAKJWhLAD
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge