name: Build and Publish Backend Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tony203/plataforma-i

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Puedes cambiar 'temurin' por otra distribución si lo prefieres
          java-version: '17'

      - name: Build with Maven
        run: mvn -f ./backend-plataforma/plataforma/pom.xml clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest ./backend-plataforma/plataforma
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        run: docker logout